version: "3.7"

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: unless-stopped
    ports:
      - 6432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentalx
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - rentx

  app:
    build:
      context: .
      dockerfile: ./Dockerfile-prod
    container_name: rentx
    restart: unless-stopped
    entrypoint: ./.docker/entrypoint-prod.sh
    env_file:
      - ./.env.prod
    ports:
      - 3333:3333
    networks:
      - rentx
    depends_on:
      - database_rentx

volumes:
  pgdata:
    driver: local

networks:
  rentx:
