version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_rentx
    restart: unless-stopped
    ports: 
      - 65432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=km*I941Y2GTgF0#AJQs^Z*$x&B
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - rentx
      
  app:
    build: .
    container_name: rentx
    entrypoint: ./.docker/entrypoint-prod.sh
    env_file:
      - ./.env.prod
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - rentx

volumes:
  pgdata: 
    driver: local

networks:
  rentx:
