version: "3.7"

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - rentx

  app:
    build: .
    container_name: rentx
    entrypoint: ./.docker/entrypoint.sh
    env_file:
      - ./.env.dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      - rentx

volumes:
  pgdata:
    driver: local

networks:
  rentx:
